name: covidcast-api
channels:
  - conda-forge
  - defaults
dependencies:
  - gdal=3.0.2
  - python=3.7.9 
  - jupyterlab 
  - pip=20.2.4
  - r-base=3.6.1
  - r-rmarkdown
  - r-devtools=2.0.2
  - r-gridextra=2.3
  - r-reticulate=1.12
  - r-blogdown
  - r-svglite
  - r-dplyr=1.0.2
  - r-ggplot2
  - r-jsonlite
  - r-httr
  - r-maptools
  - r-purrr
  - r-rlang
  - r-tidyr
  - r-vctrs
  - r-farver
  - r-vctrs
  - r-testthat
  - r-isoband
  - pandoc
  - fiona
  - geopandas
  - pandas
  - numpy
  - pillow
  - pyproj
  - matplotlib
  - pip:
    - covidcast==0.1.0